title: "Accelera Style Guide"
subtitle: ""
creator: "Accellera Systems Initiative" # E.g. the author
contributor: "" # E.g. other contributors
subject: "The Accelera Style Guide defines the recommended structure, formatting and style to develop and publish Accellera (Draft) Standards, User Guides and other standard-related documentation. This style guide serves as a reference for Accellera working groups in the technical editing process when drafting a standard-related document."
description: "The Accelera Style Guide defines the recommended structure, formatting and style to develop Accellera Standards and Drafts." # E.g. the blurb
keywords: "html, kramdown, markdown, style manual"
publisher: "Accellera Systems Initiative" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2024-01-03" # YYYY-MM-DD e.g. publication date
modified: "2024-01-03" # YYYY-MM-DD e.g. date of last revision
type: "" # e.g. Novel, Poetry, Memoir
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "Accellera Systems Initiative" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "cover.jpg"

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2024-01-03" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
    toc:
  screen-pdf:
    date: "2024-01-03" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-titlepage"
      - "0-1-introduction"
      - "0-2-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "a"
      - "b"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - file: "01"
        id: "overview"
        label: "1. Overview"
        children:
          - file: "01"
            id: "overview-purpose"
            label: "1.1 Purpose"
          - file: "01"
            id: "overview-helpful-resources"
            label: "1.2 Helpful resources"
          - file: "01"
            id: "overview-using-the-accellera-documentation-flow"
            label: "1.3 Using the Accellera documentation flow"
      - file: "02"
        id: "project-setup"
        label: "2. Project setup"
        children:
          - file: "02"
            id: "project-setup-github-repository-setup"
            label: "2.1 GitHub repository setup"
          - file: "02"
            id: "project-setup-standard-document-creation"
            label: "2.2 Standard document creation"
          - file: "02"
            id: "project-setup-tool-setup"
            label: "2.3 Tool setup"
      - file: "03"
        id: "document-authoring-and-formatting"
        label: "3. Document authoring and formatting"
        children:
          - file: "03"
            id: "document-authoring-and-formatting-use-of-markdown-and-kramdown-syntax"
            label: "3.1 Use of Markdown and Kramdown syntax"
            children:
              - file: "03"
                id: "document-authoring-and-formatting-use-of-markdown-and-kramdown-syntax-paragraphs"
                label: "3.1.1 Paragraphs"
              - file: "03"
                id: "document-authoring-and-formatting-use-of-markdown-and-kramdown-syntax-headers"
                label: "3.1.2 Headers"
              - file: "03"
                id: "document-authoring-and-formatting-use-of-markdown-and-kramdown-syntax-italics"
                label: "3.1.3 Italics"
              - file: "03"
                id: "document-authoring-and-formatting-use-of-markdown-and-kramdown-syntax-bold"
                label: "3.1.4 Bold"     
      - file: "04"
        id: "document-structure-and-style"
        label: "4. Document structure and style"
      - file: "a"
        id: "environment-setup"
        label: "Annex A (informative) Environment setup"
      - file: "b"
        id: "electric-book-commands"
        label: "Annex B (informative) Electric Book commands"
