title: "Accelera Style Guide"
subtitle: ""
creator: "Accellera Systems Initiative" # E.g. the author
contributor: "" # E.g. other contributors
subject: "" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "The Accelera Style Guide defines the recommended structure, formatting and style to develop Accellera Standards and Drafts." # E.g. the blurb
keywords: "html, kramdown, markdown, style manual"
publisher: "Accellera Systems Initiative" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2024-01-03" # YYYY-MM-DD e.g. publication date
modified: "2024-01-03" # YYYY-MM-DD e.g. date of last revision
type: "" # e.g. Novel, Poetry, Memoir
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "Accellera Systems Initiative" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "cover.jpg"

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2024-01-03" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
    toc:
  screen-pdf:
    date: "2024-01-03" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-titlepage"
      - "0-1-introduction"
      - "0-2-contents"
      - "chapter-1"
      - "chapter-2"
      - "chapter-3"
      - "chapter-4"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - file: "chapter-1"
        id: "1-overview"
        label: "1. Overview"
        children:
          - file: "chapter-1"
            id: "11-purpose"
            label: "1.1 Purpose"
          - file: "chapter-1"
            id: "12-helpful-resources"
            label: "1.2 Helpful resources"
      - file: "chapter-2"
        id: "2-project-setup"
        label: "2. Project setup"
        children:
          - file: "chapter-2"
            id: "21-github-repository-setup"
            label: "2.1 GitHub repository setup"
          - file: "chapter-2"
            id: "22-standard-document-creation"
            label: "2.2 Standard document creation"
      - file: "chapter-3"
        id: "3-document-authoring-and-formatting"
        label: "3. Document authoring and formatting"
        children:
          - file: "chapter-3"
            id: "31-use-of-markdown-and-kramdown-syntax"
            label: "3.1 Use of Markdown and Kramdown syntax"
            children:
              - file: "chapter-3"
                id: "311-paragraphs"
                label: "3.1.1 Paragraphs"
              - file: "chapter-3"
                id: "312-headers"
                label: "3.1.2 Headers"
              - file: "chapter-3"
                id: "313-italics"
                label: "3.1.3 Italics"
              - file: "chapter-3"
                id: "314-bold"
                label: "3.1.4 Bold"     
      - file: "chapter-4"
        id: "4-document-structure-and-style"
        label: "4. Document structure and style"
