title: "SystemC Configuration, Control and Inspection Standard"
subtitle: ""
version: "version 1.0"
creator: "Accellera Systems Initiative" # E.g. the author
contributor: "" # E.g. other contributors
subject: "This is the SystemC Configuration, Control and Inspection (CCI) Language Reference Manual." # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "This is the SystemC Configuration, Control and Inspection (CCI) Language Reference Manual." # E.g. the blurb
keywords: "Accellera Systems Initiative, SystemC, Configuration, CCI"
publisher: "Accellera Systems Initiative" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2018-06-01" # YYYY-MM-DD e.g. publication date
modified: "2018-06-01" # YYYY-MM-DD e.g. date of last revision
type: "Standard" # e.g. Standard, User Guide, Whitepaper
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "Accellera" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "accellera_logo.svg"
status: "Final" # status, e.g., Draft, Final

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
    toc:
  screen-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-titlepage"
      - "0-1-abstract"
      - "0-2-notice"
      - "0-3-introduction"
      - "0-4-participants"
      - "0-5-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "a"
      - "b"
      - "c"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - file: "01"
        id: "1-overview"
        label: "1. Overview"
        children:
          - file: "01"
            id: "11-scope"
            label: "1.1 Scope"
          - file: "01"
            id: "12-purpose"
            label: "1.2 Purpose"
          - file: "01"
            id: "13-word-usage"
            label: "1.3 Word usage"
      - file: "02"
        id: "2-normative-references"
        label: "2. Normative references"
      - file: "03"
        id: "3-definitions-acronyms-and-abbreviations"
        label: "3. Definitions, acronyms, and abbreviations"
        children:
          - file: "03"
            id: "31-definitions"
            label: "3.1 Definitions"
      - file: "04"
        id: "4-body-of-the-standard"
        label: "4. Body of the standard"
      - file: "a"
        id: "annex-a"
        label: "Annex A (informative) Title"
