title: "SystemC Configuration, Control and Inspection Standard"
subtitle: ""
version: "version 1.0"
creator: "Accellera Systems Initiative" # E.g. the author
contributor: "" # E.g. other contributors
subject: "This is the SystemC Configuration, Control and Inspection (CCI) Language Reference Manual." # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "This is the SystemC Configuration, Control and Inspection (CCI) Language Reference Manual." # E.g. the blurb
keywords: "Accellera Systems Initiative, SystemC, Configuration, CCI"
publisher: "Accellera Systems Initiative" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2018-06-01" # YYYY-MM-DD e.g. publication date
modified: "2018-06-01" # YYYY-MM-DD e.g. date of last revision
type: "Standard" # e.g. Standard, User Guide, Whitepaper
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "Accellera" # who owns the copyright?
rights: "All rights reserved." # e.g. a copyright statement
image: "accellera_logo.svg"
status: "Final" # status, e.g., Draft, Final

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
    toc:
  screen-pdf:
    date: "2018-06-01" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-titlepage"
      - "0-1-abstract"
      - "0-2-notice"
      - "0-3-introduction"
      - "0-4-participants"
      - "0-5-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "a"
      - "b"
      - "c"
      - "d"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - file: "01"
        id: "1-overview"
        label: "1. Overview"
        children:
          - file: "01"
            id: "11-scope"
            label: "1.1 Scope"
          - file: "01"
            id: "12-purpose"
            label: "1.2 Purpose"
          - file: "01"
            id: "13-word-usage"
            label: "1.3 Word usage"
      - file: "02"
        id: "2-normative-references"
        label: "2. Normative references"
      - file: "03"
        id: "3-terminology-and-conventions-used-in-this-standard"
        label: "3. Terminology and conventions used in this standard"
        children:
          - file: "03"
            id: "31-terminology"
            label: "3.1 Terminology"
          - file: "03"
            id: "32-syntactical-conventions"
            label: "3.2 Syntactical conventions"
      - file: "03"
        id: "33-typographical-conventions"
        label: "3.3 Typographical conventions"
      - file: "03"
        id: "34-semantic-conventions"
        label: "3.4 Semantic conventions"
      - file: "04"
        id: "4-cci-architecture-overview"
        label: "4. CCI architecture overview"
      - file: "05"
        id: "5-configuration-interfaces"
        label: "5. Configuration interfaces"
        children:
          - file: "05"
            id: "51-namespaces"
            label: "5.1 Namespaces"
          - file: "05"
            id: "52-configuration-header-file"
            label: "5.2 Configuration header file"
          - file: "05"
            id: "53-enumerations"
            label: "5.3 Enumerations"
          - file: "05"
            id: "54-core-interfaces"
            label: "5.4 Core interfaces"
          - file: "05"
            id: "55-variant-type-parameter-values"
            label: "5.5 Variant type parameter values"
          - file: "05"
            id: "56-parameters"
            label: "5.6 Parameters"
          - file: "05"
            id: "57-brokers"
            label: "5.7 Brokers"
          - file: "05"
            id: "58-error-reporting"
            label: "5.8 Error reporting"
          - file: "05"
            id: "59-name-support-functions"
            label: "5.9 Name support functions"
          - file: "05"
            id: "510-version-information"
            label: "5.10 Version information"
      - file: "a"
        id: "annex-a-informative-a-introduction-to-systemc-configuration"
        label: "Annex A <strong>(informative)</strong> A Introduction to SystemC Configuration"
        children:
          - file: "a"
            id: "a1-sample-code"
            label: "A.1 Sample code"
          - file: "a"
            id: "a2--interface-classes"
            label: "A.2  Interface classes"
          - file: "a"
            id: "a3-error-reporting"
            label: "A.3 Error reporting"
      - file: "b"
        id: "annex-b-informative-glossary"
        label: "Annex B <strong>(informative)</strong> Glossary"
      - file: "c"
        id: "annex-c-informative-systemc-configuration-modeler-guidelines"
        label: "Annex C <strong>(informative)</strong> SystemC Configuration modeler guidelines"
        children:
          - file: "c"
            id: "c1-declare-parameter-instances-as-protected-or-private-members"
            label: "C.1 Declare parameter instances as protected or private members"
          - file: "c"
            id: "c2-initialize-broker-handles-during-module-elaboration"
            label: "C.2 Initialize broker handles during module elaboration"
          - file: "c"
            id: "c3-prefer-typed-parameter-value-access-over-untyped-when-possible-for-speed"
            label: "C.3 Prefer typed parameter value access over untyped, when possible, for speed"
          - file: "c"
            id: "c4-provide-parameter-descriptions"
            label: "C.4 Provide parameter descriptions"
      - file: "d"
        id: "annex-d-informative-enabling-user-defined-parameter-value-types"
        label: "Annex D <strong>(informative)</strong> Enabling user-defined parameter value types"
